[bot]
username = "@LeadMag_NutriLive_bot"

[channel]
id = "@NutriLaive"
name = "НутриЛайф🥦🥑🥬"
invite_link = "https://t.me/NutriLaive"

[messages]
welcome = """
Привет!👋
Спасибо, что присоединился к "НутриЛайф" — каналу, где нутрициология становится доступной и интересной 📚🌍.
Мы делимся знаниями о правильном питании, микронутриентах, метаболизме и их влиянии на здоровье 💪.
И возвращайся ко мне за подарком🎁
t.me/NutriLaive
"""

lead_magnet = """
🎁 В качестве благодарности за подписку, вот полезный материал для тебя:

https://disk.yandex.ru/i/GO-xgwqozYvz0Q

Если хочешь узнать больше, запишись на бесплатную консультацию!
"""

[timing]
consultation_delay = 3600  # Задержка перед призывом на консультацию (в секундах)