[bot]
username = "@LeadMag_NutriLive_bot"

[channel]
id = "@NutriLaive"
name = "НутриЛайф🥦🥑🥬"
invite_link = "https://t.me/NutriLaive"

[messages]
welcome = """
👋 Привет! Спасибо, что присоединился к "НутриЛайф" — каналу, где нутрициология становится доступной и интересной 📚🌍. Мы делимся знаниями о правильном питании, микронутриентах, метаболизме и их влиянии на здоровье 💪. Нутрициология — это не только здоровая еда, но и понимание того, как наше тело функционирует и как мы можем поддерживать его здоровье 🌿🧠. Наши статьи основаны на последних научных данных и помогут тебе сделать осознанный выбор в пользу здоровья. Оставайся с нами и будь здоров! 🌟
"""

lead_magnet = """
🎁 В качестве благодарности за подписку, вот полезный материал для тебя:

https://disk.yandex.ru/i/GO-xgwqozYvz0Q

Если хочешь узнать больше, запишись на бесплатную консультацию!
"""

[timing]
consultation_delay = 3600  # Задержка перед призывом на консультацию (в секундах)